USE [FuelPricesDb]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FuelPrices] (
	[RecordDate] [date] NOT NULL
	,[Price] [decimal](18, 2) NOT NULL
	,CONSTRAINT [PK_FuelPrices] PRIMARY KEY CLUSTERED ([RecordDate] ASC) WITH (
		PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
		,OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
		) ON [PRIMARY]
	) ON [PRIMARY]
GO


